name: Go

on:
  push:
    branches: [ ehealth ]
  pull_request:
    branches: [ ehealth ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -buildmode=c-shared -o publish/issuer.dll issuer/cinterface/cinterface.go

    - name: Archive build results
      uses: actions/upload-artifact@v2
      with:
        name: publish-folder
        path: |
          publish
